### ISSUE TITLE
Is the catalog up-to-date?

### ISSUE THREAD

**Issue by mikkokotila** [OpenPecha/catalog#1]
I noted there were more volumes (repos starting with P000...) than there are items in the catalog. Is it intentional? Is it safe to assume that everything with P000 leading the repo name, will be a Dharma text from an authoritative source?

**Comment by eroux** [comment]
There seems to be some pechas that are indeed not in the catalog, for instance https://github.com/openPecha/P000792 . @ngawangtrinley perhaps this could be resolved?

**Comment by ngawangtrinley** [comment]
@ta4tsering will write a script to update the catalog. Our long term solution is to create pechas with an api so we are sure everything is done in a standard manner.

**Comment by ta4tsering** [comment]
catalog will be updated every sunday midnight as I have added a github action to the catalog repo to do that
